### ISSUE TITLE
Make Batchposter handle upserts for record types / APIs that do not allow upserts

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#102]
Communicate the difference in how the script handles differences among upserts

For extradata: 
Make an initial series of get requests to get any existing IDs and make PUT requests to those.

For SRS:
TBD. Need more exploring.

**Comment by kevinpowell1** [comment]
covered by https://github.com/FOLIO-FSE/folio_migration_tools/pull/804
