### ISSUE TITLE
Library configuration file: make holdingsMergeCriteria options more intuitive

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#103]
Example of current:
`"holdingsMergeCriteria": "lb",
`

Could we name the options something in clear text (e.g. "location_and_callnumber")? Would make it easier for to read and work with the config file.

**Comment by fontanka16** [comment]
Proposal for a solution:
instead of the current
`"holdingsMergeCriteria": "clb",`
use the property names from the holdingsrecords as merge criteria:
`"holdingsMergeCriteria": ["instanceId, "permanentLocationId", "callNumber"]`
