### ISSUE TITLE
Add configuration option to reset HRID settings

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#105]
- [x] Add task configuration for resetting hrid settings, meaning this needs to be set per task.
- [x] When resetting, just reset the numbers to the FOLIO default original values **for that specific object type.** Honor any other setting.

**Comment by fontanka16** [comment]
@branchedelac @bltravis @banerjek 
What do we mean with "resetting" in this context?
resetting to the FOLIO defaults is easy, but for all other cases, I do not know.  
Should we honor the prefixes always as well as the 0-settings?

**Comment by fontanka16** [comment]
Proposal in the description.

**Comment by branchedelac** [comment]
I wonder if the scripts should be touching the HRID settings Start number at all? FOLIO doesn't increment it when generating an HRID, so it is a bit confusing that our scripts do.

**Comment by branchedelac** [comment]
This is what the numbers look like after we've loaded instances, holdings and items.
![image-2.png](https://user-images.githubusercontent.com/44287646/166440343-044ceca0-9baf-454c-a8f6-32af883ea2a4.png)

**Comment by fontanka16** [comment]
Bugfest does not honor them either. Very weird
![image](https://user-images.githubusercontent.com/1894384/166453852-55342688-5296-4d4e-a7cb-aa812206c474.png)
![image](https://user-images.githubusercontent.com/1894384/166453878-03a403ad-c0be-4a1e-8e63-1cebde2837a5.png)
![image](https://user-images.githubusercontent.com/1894384/166453893-5366a344-2eaa-432c-af4f-f32a80636afb.png)

**Comment by fontanka16** [comment]
I asked about if this is being a bug or not.
