### ISSUE TITLE
Proposal: Create and save to an [iterationIdentifier] folder in migration_repo/reports 

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#110]
Create a folder with the iterationIdentifier as it's name in the /reports folder, and save all reports, logs and data error files there. 

The purpose would be to declutter the public facing reports folder, and to make sure that the documents aimed at a librarian audience (transformation reports, data error lists), are easy to locate.

migration_repo > reports > iterationIdentifier > [transformation reports]
migration_repo > reports > iterationIdentifier > data_errors > [data error files]
migration_repo > reports > iterationIdentifier > logs > [log files]

![image](https://user-images.githubusercontent.com/44287646/149916311-88a732a1-8016-4c62-90c4-a9da49406325.png)

**Comment by fontanka16** [comment]
@branchedelac my stab at this resulted in the folding folder structure:
![image](https://user-images.githubusercontent.com/1894384/191925929-9830d8a3-55be-42dd-95d8-e3dc6d9147ee.png)

It is not the perfect solution for the librarians, but I think it is a good balance between ease of navigation as well as performing the migrations. There is a PR for this now, linked above.
