### ISSUE TITLE
Implement HRID assignment for Holdings records created from MFHDs

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#137]
- [x] Instance HRID needs to be added to the instance-id-mapping file
- [x] Instance HRID must be added to the 004 of the holdingsrecord
- [x] Create a 999 with $s as the SRS uuid and $i as the Holdings UUID
- [x] HRID must be set on the Holdingsrecord.json
- [x] Create 035s for all Former Ids
- [x] Set 001 to hrid

**Comment by fontanka16** [comment]
@bltravis @branchedelac @banerjek this was more complex than I expected. I am working on this now and am trying to fix it within the next 24 hrs. The develop branch will remain broken for MFHD migrations until then.

**Comment by branchedelac** [comment]
Thank you for the info! None of the libraries I am currently working with are migrating MFHDs.

**Comment by fontanka16** [comment]
Example SRS record:
https://bugfest-kiwi.folio.ebsco.com/inventory/viewsource/09671fe2-8ee4-4c99-b9d8-59db0d279ead/12f0b34a-f971-47fd-93e7-99d300655f29?qindex=id&query=09671fe2-8ee4-4c99-b9d8-59db0d279ead&segment=instances&sort=title

**Comment by banerjek** [comment]
Alabama wants MARC MFHDs. 

Would be desirable for MFHD migrations to be able to select via config whether to be SRS backed or not -- even when source is MARC, FOLIO backed Holdings only are often desirable

**Comment by fontanka16** [comment]
@banerjek , yes this will be included in the fix via the createSourceRecords setting:
![image](https://user-images.githubusercontent.com/1894384/153375483-9cb4d7f2-5172-405f-8028-b313e2d15191.png)
