### ISSUE TITLE
Current Bound-with handling creates too many holdingsrecords when bw is used to describe hierarchical relationships...

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#138]
![image](https://user-images.githubusercontent.com/1894384/153580713-f6b75e54-a352-489f-a9ae-b4b9d84e859e.png)

**Comment by branchedelac** [comment]
This might be related: https://github.com/FOLIO-FSE/migration_lafayette_college/issues/7

**Comment by fontanka16** [comment]
![image](https://user-images.githubusercontent.com/1894384/155101839-b520abbd-8611-4e9e-97aa-4f200e7237e4.png)
