### ISSUE TITLE
Add snapshot object before and update it after running the SRS posting

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#140]
We are now using one snapshot for all postings. If it is to be "closed" (set to COMMITTED ) after a run, we can no longer create the snapshot reference as part of creating the srs records, but the Snapshot must be created when running the postings.
Proposal to implement:
1. When creating SRS records, do not add a Snapshot id to the records. Instead, add an empty placeholder for it.
2. When posting SRS, first POST a Snapshot definition with the status of PARSING_IN_PROGRESS
3. While iterating over the SRS records, add the UUID of this Snapshot object to the record instead of the placeholder
4. When posting is done, update the Snapshot and set its status to COMMITTED.

**Comment by fontanka16** [comment]
@banerjek should each SRS run start and finish with a snapshot post perhaps?

**Comment by banerjek** [comment]
@fontanka16 I like the idea of each SRS starting with the snapshot POST and ending with the snapshot PUT -- strikes me as a way to avoid strange errors later
