### ISSUE TITLE
Add external objects to data mapping file creation schemas for Organizations

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#151]
+ notes
(+ interfaces)
(+ credentials)
(+ contacts)

**Comment by branchedelac** [comment]
Depends on #294, #295, #296

**Comment by branchedelac** [comment]
Will do this as part of each individual issue in the list above.

**Comment by branchedelac** [comment]
The schemas are generated by the migration tool, but I have not added them (ie the updated org one) to the mapping file creator.

**Comment by kevinpowell1** [comment]
finished by Lisa in March 2023
