### ISSUE TITLE
Include open fee-fines migration into migration_tools

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#163]
More specifically, this migration task will deal with "manual fees/fines". This is the type that can be added on to a user record via the UI. They may or may not link to an item record. They are not, however, linked to loans.
![image](https://user-images.githubusercontent.com/44287646/234832251-4bdfc26d-5cc0-4432-b829-9fa28d7bd4ba.png)

To create manual fees/fines, you need to have configured Fee/fine owners and Manual charges>Fee/fine types
![image](https://user-images.githubusercontent.com/44287646/234832015-f82250db-d5f2-4b24-90e7-96495418b599.png)

**Comment by branchedelac** [comment]
- [ ] Create mapper
- [ ] Create transformation task
- [ ] Create tests to verify mapping
- [ ] Run task to ensure objects and reports are written
- [ ] Add FOLIO UUID lookup for item and user barcode
- [ ] Add ref data mapping for fee/fine owner and fee/fine type
- [ ] Add default fee/fine owner and fee/fine type
- [ ] Validate dates
- [ ] Hardcode some behaviour-related defaults (like Notfiy = False)

Out of scope:
- Handle ref data mapping where FOLIO returns multiple name matches (fee/fine type)
- Investigate the need for creating one fee/fine account with multiple actions (eg opened and closed)

**Comment by branchedelac** [comment]
Out of scope: 
https://github.com/FOLIO-FSE/folio_migration_tools/issues/616
https://github.com/FOLIO-FSE/folio_migration_tools/issues/617
https://github.com/FOLIO-FSE/folio_migration_tools/issues/618
