### ISSUE TITLE
Item transformation: Don't add a "notes" object when there is no a "note" property

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#165]
https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/item-storage.html#item_storage_items_post

The item transformation appears to be creating notes objects which contain nothing but a staffOnly value. While these are accepted by the API (post successful), they are (not unreasonably) treated like an error when you open the item in Edit mode in the UI. 

![image](https://user-images.githubusercontent.com/44287646/156536406-d29b9b07-01da-423c-85a4-0bd17ee0483c.png)

`{"id": "7262f446-0906-5061-bd7b-b87170352bbb", "metadata": {"createdDate": "2022-03-02T15:04:44.980", "createdByUserId": "9eb67301-6f6e-468f-9b1a-6134dc39a684", "updatedDate": "2022-03-02T15:04:44.980", "updatedByUserId": "9eb67301-6f6e-468f-9b1a-6134dc39a684"}, "hrid": "i10002777", "holdingsRecordId": "466946d5-ddc4-5069-b3d6-3ac396fe3db2", "formerIds": ["i10002777", "['1185330', '0dphh31kx8ss0z8v']"], "barcode": "60350555205", "notes": [{"staffOnly": false}], "status": {"name": "Available", "date": "2022-03-02T15:04:44.980385"}, "materialTypeId": "45e68046-3af5-410f-9177-57d3ba5be878", "permanentLoanTypeId": "816f34bc-c744-41bf-9d71-987b965ef8bc"}
`

There are no notes mapped in the mapping file I used for this. 

```
      {
         "folio_field": "notes[0].itemNoteTypeId",
         "legacy_field": "Not mapped",
         "value": "",
         "description": ""
      },
      {
         "folio_field": "notes[0].note",
         "legacy_field": "Not mapped",
         "value": "",
         "description": ""
      },
      {
         "folio_field": "notes[0].staffOnly",
         "legacy_field": "Not mapped",
         "value": false,
         "description": ""
      },
```

Philosophically, this is related to https://github.com/FOLIO-FSE/folio_migration_tools/issues/153

**Comment by fontanka16** [comment]
Great write-up @branchedelac .

**Comment by fontanka16** [comment]
@branchedelac  just looking into this. The reason for why the note is accepted without the not is because the note object has no REQUIRED properties!

I will try to create an exception

**Comment by fontanka16** [comment]
@branchedelac I added these methods into the transformers for items and csv_holdings:
```
@staticmethod
    def handle_notes(folio_object):
        if folio_object.get("notes", []):
            filtered_notes = []
            for note_obj in folio_object.get("notes", []):
                if not note_obj.get("itemNoteTypeId", ""):
                    raise TransformationProcessError(
                        folio_object.get("legacyIds", ""),
                        "Missing note type id mapping",
                        json.dumps(note_obj),
                    )
                elif note_obj.get("note", "") and note_obj.get("itemNoteTypeId", ""):
                    filtered_notes.append(note_obj)
            folio_object["notes"] = filtered_notes
```

```
    @staticmethod
    def handle_notes(folio_object):
        if folio_object.get("notes", []):
            filtered_notes = []
            for note_obj in folio_object.get("notes", []):
                if not note_obj.get("holdingsNoteTypeId", ""):
                    raise TransformationProcessError(
                        folio_object.get("legacyIds", ""),
                        "Missing note type id mapping",
                        json.dumps(note_obj),
                    )
                elif note_obj.get("note", ""):
                    filtered_notes.append(note_obj)
            folio_object["notes"] = filtered_notes
```
