### ISSUE TITLE
Non-matching values should be reported verbatim in the Migration report

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#17]
It appears that values reported as not matching reference data in FOLIO have whitespaces stripped in the migration report, making them hard to query and correct in the legacy ILS.

It needs to be verified that this is actually the root cause of issue.

![image](https://user-images.githubusercontent.com/44287646/104191371-b9a03080-541d-11eb-8473-992577de2b68.png)

**Comment by fontanka16** [comment]
@branchedelac I took a stab at this. let us see what the next reports gives

**Comment by fontanka16** [comment]
This is partly implemented, but things could be improved still.

**Comment by branchedelac** [comment]
Will do!
