### ISSUE TITLE
Consistently handle due time for III day loans to avoid duedate earlier outdate error

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#188]
[Moved from https://github.com/FOLIO-FSE/service_tools/issues/15)

Sierra and Millennium don't export due times.

```
item_barcode	out_date	due_date	renewal_count	status	patron_barcode	next_item_status
789	2019-02-22 10:53:00	2019-02-22	0	n	1234
```
Parsing the dates as datetime typically translates that to 00:00:00, which for 1-day-loans results in a duedate earlier than outdate error.

```
item_barcode	out_date	due_date	renewal_count	status	patron_barcode	next_item_status
789	2019-02-22 10:53:00	2019-02-22 00:00:00	0	n	1234
```

Should we be setting all due times to 23:59:59PM (for III and other libraries that don't provide one) to avoid this?

**Comment by fontanka16** [comment]
@branchedelac  could you check https://github.com/FOLIO-FSE/folio_migration_tools/commit/fcd8fad745d3d37e242f6b9282e3ab48eac9cde5#diff-6276fd63df8b1563f60b13aa05727af12188396505613c9a8a953311dcd34728 to see if the test covers your use case?

**Comment by fontanka16** [comment]
Actually it does not. I am adding a new test case.

**Comment by fontanka16** [comment]
Now this case is covered as well
