### ISSUE TITLE
Logging in BatchPoster for Users is weird

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#189]
Posting successful! Total rows: 1350 Total failed: 1252 created: 1185 updated: 113 in 3.68712s Batch Size: 100

The total failed does not make sense.

**Comment by bltravis** [comment]
This is probably down to the way that mod-user-import reports results. It's possible for the import to both fail AND update an existing record. Yeah…

**Comment by kevinpowell1** [comment]
test comment

**Comment by kevinpowell1** [comment]
adding and removing labels to test Monday dot com board integration

**Comment by kevinpowell1** [comment]
Reviewing logs for migration in 2024. Total failed + total updated = total rows. Closing.

```
2024-11-05 22:24:32,774	Posting successful! Total rows: 3068 Total failed: 14 created: 0 updated: 3054 in 0.108472s Batch Size: 1 Request size: 1.03KB Message from server: Users were imported successfully.	post_users	batch_poster.py:340
```
