### ISSUE TITLE
Implement subFieldDelimiter in MARC rules mapping

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#197]
If you have this in the MARC record:

![image](https://user-images.githubusercontent.com/44287646/162923109-c1c9b5df-7a7b-499e-8aa8-b2d7e9c1eacc.png)

It should be translated to this on the instance, as it is when you update the MARC record via the UI:

![image](https://user-images.githubusercontent.com/44287646/162923022-d23fd28e-b2be-4102-8008-62208a139241.png)

Currently the migration does this
![image](https://user-images.githubusercontent.com/44287646/162923441-9af23461-84d7-4bf8-a93f-1d3b6228117e.png)

**Comment by bltravis** [comment]
Is it stripping out the existing delimiters? There is a colon in the first $a and a semicolon in the first $b in the MARC

**Comment by fontanka16** [comment]
@bltravis  yes, the rules have those functions defined.

**Comment by fontanka16** [comment]
(but they could be removed, of course)

**Comment by branchedelac** [comment]
We need to implement the configuration subFieldDelimiter in the rules for the 264.

These are the rules behind the above exmaple:
`"264": [
        {
            "rules": [
                {
                    "conditions": [
                        {
                            "type": "remove_ending_punc, trim"
                        }
                    ]
                }
            ],
            "target": "publication.place",
            "subfield": [
                "a"
            ],
            "description": "Place of publication",
            "subFieldDelimiter": [
                {
                    "value": " ; ",
                    "subfields": [
                        "a"
                    ]
                }
            ]
        },
        {
            "rules": [
                {
                    "conditions": [
                        {
                            "type": "remove_ending_punc, trim"
                        }
                    ]
                }
            ],
            "target": "publication.publisher",
            "subfield": [
                "b"
            ],
            "description": "Publisher of publication",
            "subFieldDelimiter": [
                {
                    "value": " ; ",
                    "subfields": [
                        "b"
                    ]
                }
            ]
        },
        {
            "rules": [
                {
                    "conditions": [
                        {
                            "type": "remove_ending_punc, trim, trim_period"
                        }
                    ]
                }
            ],
            "target": "publication.dateOfPublication",
            "subfield": [
                "c"
            ],
            "description": "Date of publication",
            "subFieldDelimiter": [
                {
                    "value": " ; ",
                    "subfields": [
                        "c"
                    ]
                }
            ]
        },
        {
            "rules": [
                {
                    "conditions": [
                        {
                            "type": "set_publisher_role"
                        }
                    ]
                }
            ],
            "target": "publication.role",
            "subfield": [
                "a",
                "b",
                "c"
            ],
            "description": "Role of publication, defined by 2nd indicator",
            "applyRulesOnConcatenatedData": true
        }
    ],`

**Comment by bltravis** [comment]
Closed by PR #666
