### ISSUE TITLE
Create migration task for compositePurchaseOrders (Orders and PO Lines)

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#202]
The compositePurchaseOrder object
https://github.com/folio-org/acq-models/blob/master/mod-orders/schemas/composite_purchase_order.json
will create orders and POLs in FOLIO.

**Comment by branchedelac** [comment]
@bltravis I started looking at this!

- Started adding some very basic tests in a branch that I created from your branch (and merged with the latest from main), https://github.com/FOLIO-FSE/folio_migration_tools/issues/442
- It strikes me that we could get rid of some of the ref data mapping files by using that "dictionary in mapping file " feature we all looked at together last week.

A more general comment (for all, including @fontanka16 and me):
- I think we should strive to sort (especially positional) arguments from general to specific. For example in the mapper classes. That way when we reuse/copy a method we can remove/replace the ones at the end. Will also simplify test-writing.
