### ISSUE TITLE
Make Id field and requestPreference optional when processing users

### ISSUE THREAD

**Issue by bltravis** [FOLIO-FSE/folio_migration_tools#205]
For the purposes of users iteration using mod-user-import (without deleting existing user records), it is cleaner if we don't include the user's `id` (UUID) in the generated JSON objects (I believe this is why we get errors about creating permissions). The same goes for `requestPreference` (I believe the bug that removed it if it wasn't included in the payload [has been fixed](https://issues.folio.org/browse/MODUIMP-42))

**Comment by fontanka16** [comment]
@bltravis  how does this affect User notes that are tied to the user UUID?
I am confused.

**Comment by fontanka16** [comment]
@bltravis  do you think it works, but that it just throws errors?
