### ISSUE TITLE
Add reporting on DateTime parsing results for Circulation transaction tasks

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#211]
For all dates, add a breakdown to the migration report on what the source string was and what the resulting date became.

Optionally, a third column for the UTC-conversion.

**Comment by branchedelac** [comment]
Printing out converted strings for every transaction leads to this section taking up a lot of space in the report. We may consider providing some sort of summary/illustrative sample of the conversion instead.

**Comment by kevinpowell1** [comment]
date conversions usually occur before the reports are generated
