### ISSUE TITLE
Make sure Holdings SRS records are getting their leaders validated

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#221]
DoD:

- [ ] Make a call to BibTransformer.set_leader(): and add the MFHD Marc record as an arguement together with the migration_report
- [ ] Create a test MFHD record mimicking the test_set_leader() in test_bib_transformer.py
- [ ] Run test. Done

**Comment by bltravis** [comment]
As we're not planning to support migration of MFHD source records, I'm going to go ahead and close this issue.
