### ISSUE TITLE
Migrate open loans task skips first loan (row) when creating loams

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#236]
There is a configuration property, start_row, which instructs the migration tool on whether to skip any rows in the legacy data when creating loans. 

This parameter is set to "1" default, which may be a remnant from when the loans creation would start from a tsv file with headers, rather than the list of loans now created by the validation process. The use case for the configurable start row is that, if your loans migration crashes mid-run, you do not have to start over from the beginning.

Possible solution(s):
1. Set default value to 0
2. Use the parameter (+ 1 for the header row) when validating the loan file rather than when creating the loans

**Comment by fontanka16** [comment]
Fixed. Will come as part of next release
