### ISSUE TITLE
Configuration error reporting reports wrong search location for MARC bibs in BibTransformer

### ISSUE THREAD

**Issue by bltravis** [FOLIO-FSE/folio_migration_tools#238]
If there is an error that prevents the BibTransformer job from finding the configured file(s), the error reporting indicates that the files could not be found in <migration repo>/data/items, rather than …/data/instances:

eg. `2022-05-09 04:04:56,861 CRITICAL        Files 050322_Laf_all_unsuppressed_bibs.mrc,050322_Laf_bibs_supressed.mrc not found in /home/ssm-user/client_data/migration_lafayette_college/data/items  __main__.py:79
`

**Comment by fontanka16** [comment]
Fixed this. Will come in the next release
