### ISSUE TITLE
Failed bib records file overwritten for each file in bib transformation task

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#252]
The unique name of the file, "failed_bib_records_iteration_YYYYMMDD.mrc" is assigned once for the entire task, but the file is actually opened/created anew for every data file included in the task. 

The result is that the failed records from data file 1 will be overwritten by those in data file 2, and so on.

![image](https://user-images.githubusercontent.com/44287646/169400407-be4479e5-4624-4b29-a6c6-38501e1678f3.png)

**Comment by bltravis** [comment]
I've created a [branch for this fix](https://github.com/FOLIO-FSE/folio_migration_tools/tree/Issue_252_fix_overwritten_failed_bibs). Will try to submit the pull request on Thursday. Need to test it with sample data.
