### ISSUE TITLE
Make LoansPoster UTC offset handling DST-aware

### ISSUE THREAD

**Issue by bltravis** [FOLIO-FSE/folio_migration_tools#279]
When posting loans with a UTC offset ("utcDifference"), the time adjustments are not DST (daylight-saving time) aware (eg. EDT is UTC-04:00, whereas ET is UTC-05:00. This results in due dates and out dates that are off by one hour for either standard time or DST, depending on which utcDifference value is specified.

**Comment by fontanka16** [comment]
@bltravis so adding the timezone code instead the diff would be better, right? And then using some library to transform the timestamps to UTC. Should be fairly easy and better to work with from the Data migrator's side.

**Comment by bltravis** [comment]
@fontanka16 Sorry, missed this comment. That's my thinking. Current plan is to:

- Modify task configuration to include retrieving the tenant timezone from mod-configuration
- Continue to parse due_date and out_date
- If timezone is not included in the parsed dates
- Set timezone to tenant timezone

Question:
Do we need to go ahead and convert to UTC timestamps before submitting to FOLIO?

**Comment by fontanka16** [comment]
@bltravis I believe that we must post UTC if that is what you are asking

**Comment by fontanka16** [comment]
This is great!
