### ISSUE TITLE
When creating Organizations, create Contacts as extradata

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#294]
This includes adding the newly enhanced schema to the mapping-file-creator.

**Comment by branchedelac** [comment]
Proposed sequence of events:

1. Mapping: the OrganizationMapper fetches the Contacts schema and integrate it into
2. Mapping: during mapping transformation, the contact (objects are built similar to other array objects)
3. Post-processing: take the objects in the Contacts array and save them as extra data 
4. Post-processing: removes everything except the UUID string(s) from the Contacts array

**Comment by fontanka16** [comment]
@branchedelac I like this strategy!

**Comment by branchedelac** [comment]
Another option:

1. Mapping: the OrganizationMapper treats the contacts as a an array of strings (which it is)
2. Mapping: during mapping transformation, a UUID is added to the Contacts array for each mapped contact
3. Post-processing: for each uuid, a contacts object bearing this UUID is created based on the contacts schema (a contacts mapper?) and printed as extradata. 

Taking these independent objects out of the depths of organization mapping might make the code a bit easier to follow.
The downside is the contacts are not -- out of the box, but it could be done -- included in the mapping file. On the other hand, the Orgs mapping file creation UX is already so overwhelming I am a bit concerned about adding more stuff.

**Comment by fontanka16** [comment]
@branchedelac this seems more on-par with how Notes are done, except for the mapping part I guess.

**Comment by fontanka16** [comment]
So this (also) seems like a good approach.

**Comment by branchedelac** [comment]
I think Contacts on Organizations are very much like Notes (except one of them that _**is**_ Notes), with a few exceptions:

- They link is from the organization to the sub-object, not the other way around. Comparable to Instructors, I think.
- They contain many of the same sub-objects as the Organization itself, like "addresses".
- They are not (currently) shared with any other apps.

How is mapping handled for Notes?

**Comment by branchedelac** [comment]
Are the notes still extra data?

**Comment by fontanka16** [comment]
> Are the notes also extra data?

Yes. See the NotesMapper

**Comment by fontanka16** [comment]
> How is mapping handled for Notes?
Follow the calls to NotesMapper.map_notes()

**Comment by branchedelac** [comment]
I was wondering if you could give me a summary to speed things up.

**Comment by branchedelac** [comment]
Broke this out as a bug issue (not a showstopper): https://github.com/FOLIO-FSE/folio_migration_tools/issues/464

**Comment by branchedelac** [comment]
Broke this out: https://github.com/FOLIO-FSE/folio_migration_tools/issues/468
