### ISSUE TITLE
Make Organization schema in Mapping file creator Lotus-compliant

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#298]
The major difference between Kiwi->Lotus is that the Edi properties get moved into an object, which should only be used if isVendor=True.

**Comment by branchedelac** [comment]
test update

**Comment by branchedelac** [comment]
When I tried to do this I realized the edi property is still there. ﻿Asked for clarification in https://issues.folio.org/browse/UIORGS-280

**Comment by branchedelac** [comment]
Got confirmation in Jira that the schema is not changing.

**Comment by fontanka16** [comment]
Good to have it solved.
