### ISSUE TITLE
When creating Users never set more than one address as "primary"

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#301]
@fontanka16 suggests raising a transformationProcessError.

_Then, make sure that the code actually raises the error. A transformationProcess error that halts the script seems a good option to me, since the issue is likely mapping-related, right?_  (https://github.com/FOLIO-FSE/folio_migration_tools/pull/300)

I think it could be a data issue as well as a mapping issue, Imagine this:

It could be a mapping issue if you mapped like this
`"address[0].isPrimary": true
"address[1].isPrimary": true `

But a data issue if you mapped like this:
`"address[0].isPrimary": "address_1_primary"
"address[1].isPrimary": "address_2_primary" `

and your data like this
`
address_1_city	address_1_primary	address_2_city	address_1_primary
Göteborg	true	Hudiksvall	false
Göteborg	false	Hudiksvall	true
Göteborg	false	Hudiksvall	false
Göteborg	true	Hudiksvall	true
`

**Comment by fontanka16** [comment]
Proposal: 
1. Add check for mapping and raise transformationProcessError
2. Add check for multiple primary addresses and fail those records (transformationRecordFailed error)

**Comment by fontanka16** [comment]
@branchedelac  seems like you have solved this for organizations now, right? I am renaming this to only deal with user addresses. Ok?
