### ISSUE TITLE
Adapt tools to Morning Glory

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#329]
[Morning Glory Release notes](https://wiki.folio.org/display/REL/Morning+Glory+%28R2+2022%29+Release+Notes)
**Known things affecting the tools**
- [ ] Something 
- [ ] Something else

**Changes to Schemas**
- [ ] Something
- [ ] Someting else

**Programming tasks**    
(to become own Github Issues)
- [x] Remove Kiwi references from the code base
- [x] Add FOLIO Release Enum for Morning Glory in configuration

**Comment by branchedelac** [comment]
Broke "Add FOLIO Release Enum for Morning Glory in configuration" out into https://github.com/FOLIO-FSE/folio_migration_tools/issues/414

**Comment by fontanka16** [comment]
Added #421 as well. @branchedelac when adding the new flower release, I think it makes sense to try to remove the deprecated ones from the code base as well..

**Comment by bltravis** [comment]
@fontanka16 @branchedelac Would we consider this issue complete, seeing as how we're onto Nolana now 😄 ?
