### ISSUE TITLE
Placeholder issue for Records in File before parsing

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#331]

**Comment by fontanka16** [comment]
@branchedelac  is this the same as https://github.com/FOLIO-FSE/folio_migration_tools/issues/339

**Comment by branchedelac** [comment]
Not sure -- it looks like you created this issue and I do not understand from the title of this one what it actually wants you to do with "Records in File before parsing".

If I had anything to do with the creation of this ticket it could be about making the counts under the General Statistics header in the various reports more consistent, precise, and phrased in a way that makes it easy for a librarian to understand what is what. 

The two key numbers the library (and IC) will look for here is:

1. How many MARC records/rows were in the legacy data file provided by the library
2. How many FOLIO records were created
