### ISSUE TITLE
Count number of rows in CSV/TSV file before feeding them to the CSV Dictreader 

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#339]
There are occasions where there are more rows in the file than what the CSV dictreader thinks. This needs to be highlighted to the report

- [ ] OS agnostic
- [ ] Propagate results to report
- [ ] Optional: Use for percentage calculations in progress meters

**Comment by fontanka16** [comment]
@bltravis MappingFileMapperBase has this get_objects where this could be implemented. 
I realized a thing that would be really handy as well, and that is for that function to warn for empty rows. As it is now, the dictreader throws a really weird exception

**Comment by fontanka16** [comment]
Hmm, https://stackoverflow.com/questions/27707581/why-does-csv-dictreader-skip-empty-lines contradicts what I am seeing.

**Comment by bltravis** [comment]
@fontanka16 Yeah, that's where I'm working on putting it. I'm presently trying to get past (psychologically) the need to instantiate two different reader objects to accomplish this. The original approach I was looking at doesn't get what we actually want, so I'm looking at using a file reader to count the lines, not a csv reader. I should be able to add a check for empty lines to the line counter.

**Comment by fontanka16** [comment]
I did some quick googling before the summer, and could not find anything better.
