### ISSUE TITLE
Loans migrator needs to add timestamps

### ISSUE THREAD

**Issue by banerjek** [FOLIO-FSE/folio_migration_tools#340]
Whenever loan checkout or due dates only contain a day, loans migrator needs to add timestamp. 

Starting in lotus, failure to provide timestamp results in 500 error when POSTing

**Comment by banerjek** [comment]
This is probably handled. At the time I wrote this, I was migrating a loan file that did not include timestamps. When these were passed through verbatim, it generated a 500 -- which disappeared if a timestamp we're appended to the due date.

If you think this has been handled, I'm sure it has been. It's super obvious when you're experiencing the problem

**Comment by bltravis** [comment]
Fixed in #285
