### ISSUE TITLE
Ensure that properties required in the schema are honoured on all levels

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#464]
Whichever the level, remove any object where at least one of the required properties has an empty ("") value.

![image](https://user-images.githubusercontent.com/44287646/210794164-0dcf8246-5e89-44df-a86d-dee144ed5659.png)

**Comment by branchedelac** [comment]
Compare with record level emails which are only saved if they contain the required value
![image](https://user-images.githubusercontent.com/44287646/210794966-381bf725-dfe2-4bb7-8687-faf8f4fc85e5.png)

**Comment by branchedelac** [comment]
Here is an example from instances, where a missing required "uri" property in the Electronic access object caused the following posting error:
```
	{
    "errors
    ": [
        {
            "message": "must not be null",
            "type": "1",
            "code": "javax.validation.constraints.NotNull.message",
            "parameters": [
                {
                    "key": "instances[0].electronicAccess[0].uri",
                    "value": "null"
                }
            ]
        }
    ]
}	
```

Compare schema
![image](https://user-images.githubusercontent.com/44287646/216581156-44fc85e8-1ebd-40bd-aa0d-cb7e2dda7c25.png)

**Comment by branchedelac** [comment]
Might be worth noting that all the examples I've listed above involve arrays.

**Comment by branchedelac** [comment]
@fontanka16 I think this works fixed for arrays of strings now.

However, if the array contains an object (or maybe an array?): #531

**Comment by fontanka16** [comment]
Needs to be split in more detailed issues
