### ISSUE TITLE
Make mapper map array > object > object > string

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#502]

**Comment by branchedelac** [comment]
Status: Created branch, created test, tried to solve, made test succeed, made other tests fail.

**Comment by fontanka16** [comment]
@branchedelac  see the commit referenced above. It seems it was the properties without types that made it fail.

**Comment by branchedelac** [comment]
@fontanka16  What do you mean by "properties without a type"? I wonder if there was an error in the test? 

Looking at https://github.com/folio-org/acq-models/blob/master/mod-orgs/schemas/interface_credential.json -- which is where I encountered this -- all the properties (except id, but I've seen that in other schemas) appear to have types.

**Comment by fontanka16** [comment]
Here is one example from the Composite POL:
![image](https://user-images.githubusercontent.com/1894384/220052449-b5edaced-2c6f-4ca2-b75a-3a974a64e739.png)

There were others as well. Let me look them up. Or, could this have happened in the code somehow?

**Comment by branchedelac** [comment]
Did you look at the test and changes I made to this branch?

In the test schema I didn't include any of the "id" fields.

![image](https://user-images.githubusercontent.com/44287646/220061870-eaefefd2-1fc3-41a1-9e3a-6d6954b3c599.png)

**Comment by branchedelac** [comment]
Or were you saying that the missing types is what made the _other_ tests in this branch fail after I'd made the new one run successfully?

**Comment by fontanka16** [comment]
Yes. Exactly.

**Comment by branchedelac** [comment]
@fontanka16 Have you merged the fix for this into main yet? I need it to go ahead with my organization work.

**Comment by fontanka16** [comment]
Not yet!

**Comment by branchedelac** [comment]
Apart from the original issue, I am also noticing some oddness wrt validating required properties for more deeply nested objects (the required properties of on the middle level are forgotten when you go a level deeper, before the actual validation occurs). But I don't want to dig to deep knowing that the method has already changed.
