### ISSUE TITLE
When matching of Contributor type string fails, add the string to the freetext field of the contributor type. i

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#523]
- [ ] Do the above
- [ ] Add this to the report

**Comment by bltravis** [comment]
Do you mean just add it to the reference data table for contributor type?

**Comment by branchedelac** [comment]
Nope, add the string to the free text contributor type field on the instance record.

**Comment by bltravis** [comment]
Thanks for the clarification.

**Comment by fontanka16** [comment]
Now it came back to me. We did this by implementing the AlternativeMappaing in #498
`"alternativeMapping": {
            "target": "contributors.contributorTypeText",
            "subfield": [
              "e"
            ],
            "ignoreSubsequentSubfields": true
          },`
