### ISSUE TITLE
Implement Notes handling for Composite Orders

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#530]

**Comment by branchedelac** [comment]
Note that notes are linked to the POL rather than the PO.
![image](https://user-images.githubusercontent.com/44287646/222138382-65fe8ef1-1261-44c8-b878-a78aaa6854db.png)

**Comment by branchedelac** [comment]
@fontanka16 I am not sure how best to add the UUIDs of the POLs to the order. The id is an optional property in the de-referenced purchaseOrderLine object. Can it be a random uuid or should it be generated based on some value?
