### ISSUE TITLE
Record POST fails if classificationTypeId provided but classificationNumber is null

### ISSUE THREAD

**Issue by banerjek** [FOLIO-FSE/folio_migration_tools#538]
Affects both batch and single record POST operations. 

To duplicate:
`{"metadata": {"createdDate": "2023-02-27T16:15:31.313", "createdByUserId": "082326e4-61ac-4e42-a6fc-a82a5ede076c", "updatedDate": "2023-02-27T16:15:31.313", "updatedByUserId": "082326e4-61ac-4e42-a6fc-a82a5ede076c"}, "id": "588ca842-7faa-52b4-9ae4-17a36adecd19", "hrid": "3062181", "administrativeNotes": ["Identifier(s) from previous system: 3062181"], "identifiers": [{"identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422", "value": "974958953x"}, {"identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace", "value": "3062181"}, {"identifierTypeId": "e7c92ace-a825-4187-a936-1d895e172dc3", "value": "a-th---"}], "classifications": [{"classificationTypeId": "42471af9-7d25-4f3a-bf78-60d29dcf463b"}], "contributors": [{"contributorNameTypeId": "2b94c631-fca9-4892-a730-03ee529ffe2a", "contributorTypeId": "9f0a2cf0-7a9b-45a2-a403-f68d2850d07c", "contributorTypeText": "Contributor", "primary": true, "name": "Bunchu\u0304 Ro\u0304tc\u030chanasathi\u0304an"}], "title": "P\u0153\u0304t khumsap se\u0304tthakit phichit khwa\u0304mya\u0304kc\u030chon  / Bunchu\u0304 Ro\u0304tc\u030chanasathi\u0304an.", "indexTitle": "P\u0153\u0304t khumsap se\u0304tthakit phichit khwa\u0304mya\u0304kc\u030chon", "publication": [{"place": "Krung The\u0304p :", "publisher": "Ne\u0304chan Buk International ,", "dateOfPublication": "2546 [2003] "}], "physicalDescriptions": ["276 p. : ill. ; 21 cm."], "source": "MARC", "instanceFormatIds": [], "instanceTypeId": "30fffe0e-e985-4144-b2e2-1e8179bdb41f", "modeOfIssuanceId": "9d18a02f-5897-4c31-9106-c9abb5c7ae8b", "languages": ["tha"], "discoverySuppress": true, "staffSuppress": false}`

POST fails with `{"errors":[{"message":"must not be null","type":"1","code":"javax.validation.constraints.NotNull.message","parameters":[{"key":"classifications[0].classificationNumber","value":"null"}]}]}`

Recommend deleting offending field and logging Instance UUID and removed data. Note that this information will still get into SRS.

**Comment by branchedelac** [comment]
Covered in #536
