### ISSUE TITLE
Record POST fails if electronicAccess[]relationshipId provided but uri is null

### ISSUE THREAD

**Issue by banerjek** [FOLIO-FSE/folio_migration_tools#539]
Affects both batch and single record POST operations.

To duplicate:
`{"metadata": {"createdDate": "2023-02-27T16:16:27.243", "createdByUserId": "082326e4-61ac-4e42-a6fc-a82a5ede076c", "updatedDate": "2023-02-27T16:16:27.243", "updatedByUserId": "082326e4-61ac-4e42-a6fc-a82a5ede076c"}, "id": "98e74f9e-dca3-5c1c-ab10-26288a886146", "hrid": "7509475", "administrativeNotes": ["Identifier(s) from previous system: 7509475"], "identifiers": [{"identifierTypeId": "913300b2-03ed-469a-8179-c1092c991227", "value": "2208-9756"}, {"identifierTypeId": "2e8b3b6c-0e7d-4e48-bca2-b0b23b376af5", "value": "ISSN/JAN2018"}, {"identifierTypeId": "514f8f4a-be41-4a07-bf05-af96f93b3fd5", "value": "ISSN/JAN2018 ISSN/JAN2018"}, {"identifierTypeId": "dfc80c64-c34c-4a55-ae2c-9decc6797ba9", "value": "ISSN/JAN2018 ISSN/JAN2018"}, {"identifierTypeId": "82679eef-7fbb-4e51-94eb-65b5907b12f4", "value": "ISSN/JAN2018 ISSN/JAN2018"}, {"identifierTypeId": "24e08215-6312-4de0-8c03-1ab8644d5bfe", "value": "ISSN/JAN2018 ISSN/JAN2018"}, {"identifierTypeId": "b61e2751-b706-481f-a655-44293c248f9e", "value": "ISSN/JAN2018"}, {"identifierTypeId": "d197417f-5bd6-4779-a859-087ed74a3986", "value": "ISSN/JAN2018"}, {"identifierTypeId": "439bfbae-75bc-4f74-9fc7-b2a2d47ce3ef", "value": "(OCoLC)849266708"}, {"identifierTypeId": "3e1cf021-70b3-4f1b-83e4-48447bacf901", "value": "anuc"}, {"identifierTypeId": "e7c92ace-a825-4187-a936-1d895e172dc3", "value": "u-at-vi"}], "classifications": [{"classificationTypeId": "42471af9-7d25-4f3a-bf78-60d29dcf463b", "classificationNumber": "797.1099455"}], "alternativeTitles": [{"alternativeTitleTypeId": "30512027-cdc9-4c79-af75-1565b3bd888d", "alternativeTitle": "Watermark (Wantirna, Vic.)"}], "title": "Watermark : the Eildon Boat Club experience.", "indexTitle": "Watermark : the eildon boat club experience.", "publication": [{"place": "Eildon, Vic.", "publisher": "Eildon Boat Club,", "dateOfPublication": "2012-", "role": "Publication"}], "physicalDescriptions": ["volumes : illustrations ; 30 cm."], "publicationFrequency": ["Quarterly"], "instanceFormatIds": ["8d511d33-5e85-4c5d-9bce-6e3c9cd0c324"], "publicationRange": ["Issue 1 (June-July 2012)-"], "notes": [{"instanceNoteTypeId": "6a2533a7-4de2-4e64-8466-074c2fa9308c", "note": "Title from cover", "staffOnly": false}, {"instanceNoteTypeId": "1d51e8b2-dee7-43f5-983c-a40757b9cdfa", "note": "Also available online. Address as at 03/01/18: https://www.eildonboatclub.com.au/club-magazine/", "staffOnly": false}], "subjects": ["Eildon Boat Club Periodicals", "Boats and boating Victoria Eildon, Lake Periodicals"], "contributors": [{"contributorNameTypeId": "2e48e713-17f3-4c13-a9f8-23845bb210aa", "contributorTypeId": "97082157-5900-4c4c-a6d8-2e6c13f22ef1", "contributorTypeText": "Contributor", "primary": false, "name": "Eildon Boat Club"}], "electronicAccess": [{"relationshipId": "3b430592-2e09-4b48-9a0c-0636d66b9fb3"}], "source": "MARC", "instanceTypeId": "6312d172-f0cf-40f6-b27d-9fa8feaf332f", "modeOfIssuanceId": "068b5344-e2a6-40df-9186-1829e13cd344", "languages": ["eng"], "discoverySuppress": true, "staffSuppress": false}`

POST fails with `{"errors":[{"message":"must not be null","type":"1","code":"javax.validation.constraints.NotNull.message","parameters":[{"key":"electronicAccess[0].uri","value":"null"}]}]}`

Recommend deleting offending field and logging Instance UUID and removed data. Note that this information will still get into SRS.

**Comment by branchedelac** [comment]
Covered in #536
