### ISSUE TITLE
Repost of records in failed batches should be multithreaded

### ISSUE THREAD

**Issue by banerjek** [FOLIO-FSE/folio_migration_tools#540]
After a failed batch, records are currently posted one at a time -- this can lead to processes that run for days when there are sufficient failed records in the batches. 

Multithreading would speed things up dramatically. If HTTP responses from batches (5? 10?) were compiled before being released to the screen, logs, etc, the process would look much like it does now, only faster.

**Comment by fontanka16** [comment]
@bltravis @banerjek Closing this issue as won't do, and adding a new issue for the introduction of a re-posting toggle.
