### ISSUE TITLE
Make trimming of trailing spaces that are part of the OCLC number consistent between bib 001 and mfhd 004

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#557]
Some OCLC record numbers have trailing "filler" spaces. The migration tools are currently stripping these off the number if the value is found in bib 001, but not if it's in bib 004.

This results in a failure to match MFHDs to instances using the instance ID map, where MFHD 004 "ocm00000514\" =/= bib 001 "ocm00000514"

From my testing in Nolana bugfest, it looks like trailing spaces do not get stripped off the bib 001s. To ensure IDs match as expected post-migration, we might want to make behaviour consistent with FOLIO DI/QM.

**Comment by bltravis** [comment]
I think we can actually approach this from two sides. We can change how the 001 -> 035 transform works, to preserve spaces, and also continue to strip whitespace from the 001 value when creating the instance id map, and do the same to the 004 value when using it to look up values from the map.

**Comment by bltravis** [comment]
Ok. It looks like the 001->035 behavior is preserving the field value as-is. We just need to update the id map lookup for the 004 value to strip whitespace, since the id map constructor for instances does strip whitespace from the legacy id value.
