### ISSUE TITLE
Improve performance for ItemsTransformer by calling super().get_prop() only when needed.

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/folio_migration_tools#569]
Things to look into:

- [ ] Call super().get_prop() only when needed in ItemMapper's get_prop() method
- [ ] Look over the implementation for mapping_file_mapper_base.is_set_or_bool_or_numeric() and see if there is anything that could speed it up.

Items transformer seems significantly slower in recent releases. Nothing apparent stands out, but I recommend running a profiling on the task:

> python3 -m cProfile -o item_transformer_prof.prof -m folio_migration_tools mapping_files/configuration.json transform_items --base_folder_path ./

And then installing snakeviz 

> pip install snakeviz

 and run 

> snakeviz item_transformer_prof.prof

![image](https://user-images.githubusercontent.com/1894384/228223411-9d14fee5-3926-457e-9b9f-250192c0d810.png)

**Comment by bltravis** [comment]
Regarding task 2, I didn't see anything obvious to do in the is_set_or_bool_or_numeric method.
