### ISSUE TITLE
Unmapped fields with a fixed value do not undergo the reference data mapping

### ISSUE THREAD

**Issue by inkuss** [FOLIO-FSE/folio_migration_tools#614]
Consider transformation of CSV/TSV files into Items (https://folio-migration-tools.readthedocs.io/en/latest/migration_tasks.html#id29). Setting up this step in the Library Configuration:

{
            "name": "transform_csv_items",
            "migrationTaskType": "ItemsTransformer",
            "itemsMappingFileName": "item_mapping_for_mfhd_attached_items.json",
            "locationMapFileName": "locations.tsv",
            "callNumberTypeMapFileName": "call_number_type_mapping.tsv",
            "defaultCallNumberTypeName" : "Signatur",
            "materialTypesMapFileName": "material_types_csv.tsv",
            "loanTypesMapFileName": "loan_types_csv.tsv",
            "itemStatusesMapFileName": "item_statuses.tsv",
            "hridHandling": "preserve001",
            "files": [
                {
                    "file_name": "items_linked_to_mfhds.csv"
                }
            ]
        },

Items CSV file looks like this:
cat items_linked_to_mfhds.csv | more
ACCESSION_NUMBER,CALL_NUMBER_TYPE_ID,ITEM_ID,ITEM_LEVEL_CALL_NUMBER,ITEM_TYPE_ID,MFHD_ID,YEAR
"2018, 159",?CallNumberType_Signatur?,ia0000002,"Mb 8, 28",?MaterialType_Monographie?,la0000002,2017
"2019, 115",?CallNumberType_Signatur?,ia0000001,"Ob 33, 98",?MaterialType_Monographie?,la0000001,2019
...

LOAN_TYPE_ID is not a field in the Items CSV file. In this example, LOAN_TYPE_ID is the same for all items. 
I set LOAN_TYPE_ID as a fixed value in the Mapping JSON file:
Edit item_mapping_for_mfhd_attached_items.json
         {
          "folio_field": "permanentLoanTypeId",
           "legacy_field": "Not mapped",
            "value": "?LoanType_Praesenzbestand?",
             "description": ""
           },

Mapping files look like this:
cat loan_types_csv.tsv
folio_name      LOAN_TYPE_ID
Präsenzbestand  ?LoanType_Praesenzbestand?
Reading room    ?LoanType_ReadingRoom?
Reading room    33
Can circulate   42
Can circulate   *

cat material_types_csv.tsv
folio_name      ITEM_TYPE_ID
sound recording 33
video recording 42
Monographie     ?MaterialType_Monographie?
Zeitschrift     ?MaterialType_Zeitschrift?
Aufsatz ?MaterialType_Aufsatz?
book    *

cat call_number_type_mapping.tsv
folio_name      CALL_NUMBER_TYPE_ID
Dewey Decimal classification    8
Signatur        ?CallNumberType_Signatur?
Other scheme    *

Then, executing the step "transform_csv_items"
 python3 -m folio_migration_tools mapping_files/mokConfig.json --base_folder_path ./ transform_csv_items

leads to this Items JSON file in the results folder:
cat folio_items_transform_csv_items.json | more
{"id": "4003436e-c29a-53bd-8ef8-75660af9ad37", "metadata": {"createdDate": "2023-05-02T12:50:42.366", "createdByUserId": "20f27cb7-fc6c-4fc3-a1fa-88480b644493", "updatedDate": "2023-05-02T12:50:42.366", "updatedByUserId": "20f27cb7-fc6c-4fc3-a1fa-88480b644493"}, "hrid": "ia0000002", "holdingsRecordId": "7df8485b-e7db-56ec-85e0-c342b4cdd095", "formerIds": ["ia0000002", "la0000002"], "accessionNumber": "2018, 159", "itemLevelCallNumber": "Mb 8, 28", "itemLevelCallNumberTypeId": "0bf694a6-6096-4ec1-9de1-c780082638e5", "yearCaption": ["2017"], "itemIdentifier": "ia0000002", "status": {"name": "Available", "date": "2023-05-02T12:50:42.366623"}, "materialTypeId": "e0a50399-37d5-44fd-8819-7a1d3e1f170c", "permanentLoanTypeId": "?LoanType_Praesenzbestand?"}
{"id": "970ad02c-436f-5251-9e52-920130e1fe3f", "metadata": {"createdDate": "2023-05-02T12:50:42.367", "createdByUserId": "20f27cb7-fc6c-4fc3-a1fa-88480b644493", "updatedDate": "2023-05-02T12:50:42.367", "updatedByUserId": "20f27cb7-fc6c-4fc3-a1fa-88480b644493"}, "hrid": "ia0000001", "holdingsRecordId": "5aa0f43e-16e5-5228-b88d-d5fc1df6930b", "formerIds": ["ia0000001", "la0000001"], "accessionNumber": "2019, 115", "itemLevelCallNumber": "Ob 33, 98", "itemLevelCallNumberTypeId": "0bf694a6-6096-4ec1-9de1-c780082638e5", "yearCaption": ["2019"], "itemIdentifier": "ia0000001", "status": {"name": "Available", "date": "2023-05-02T12:50:42.367463"}, "materialTypeId": "e0a50399-37d5-44fd-8819-7a1d3e1f170c", "permanentLoanTypeId": "?LoanType_Praesenzbestand?"}
...

Looking at this:
- The call number type has been substituted: ?CallNumberType_Signatur? => 0bf694a6-6096-4ec1-9de1-c780082638e5
- The material type id has been substituted : ?MaterialType_Monographie? => e0a50399-37d5-44fd-8819-7a1d3e1f170c
- Loan type id has not been substituted: ?LoanType_Praesenzbestand?

Obviously, the mapping algorithm is not being applied if the field is not contained in the Items CSV file items_linked_to_mfhds.csv.

But I find it desirable to have the mapping algorithms also applied to fields, which are only being assigned a value in the items mapping file item_mapping_for_mfhd_attached_items.json.
I could directly assign a UUID in the items mapping file, to get around the mapping.
But then, the mapping setup is machine dependent, i.e. different on a test- and on a production server.
It is generally not such a good idea to have the UUID directly in a mapping file.

**Comment by bltravis** [comment]
@inkuss The tools are behaving as designed. For the situation you describe, you will need to choose a field that is present in the source data (eg. ITEM_TYPE_ID) and use a wildcard ("*") in the item type mapping file. Alternatively, you could set the UUID of the desired loan type as the "value" in the field mapping configuration.
