### ISSUE TITLE
Investigate implications and requirements for migrating fees/fines that are Closed/Paid

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#617]
Can you just make the status closed? Would you need to create one "billed" action and one "closed" action?

**Comment by branchedelac** [comment]
The current thin thread implementation just sets any fee/fine where remaining amount <= 0 to Closed. Hopefully this should work in most cases.

**Comment by kevinpowell1** [comment]
Out of scope
