### ISSUE TITLE
mapping_file_mapper_base.py: some properties are being mapped n times

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#628]
The symptom:
![image](https://github.com/FOLIO-FSE/folio_migration_tools/assets/44287646/58b05819-ca0e-451c-8416-c851994a8389)

The cause?
![image](https://github.com/FOLIO-FSE/folio_migration_tools/assets/44287646/165e720b-a881-4ff8-98e4-39457332ee30)

**Comment by kevinpowell1** [comment]
merged in #634
