### ISSUE TITLE
Orders process hangs (~30 min) before build start

### ISSUE THREAD

**Issue by banerjek** [FOLIO-FSE/folio_migration_tools#631]
When building orders for NLA, the process can hang for as much as a half hour before the first order line gets processed. They only have ~3K orders, and since I didn't also encounter this problem with Douglas, I suspect it's related to the 80K organizations they have or that something is mapped for them that is not mapped for Douglas

When the process is hanging, there is no evidence of excessive CPU, memory, or disk use. Note time stamps between display of mapped fields and next step
![order_build](https://github.com/FOLIO-FSE/folio_migration_tools/assets/89302/a43d34cd-46ef-4899-b1b7-5ec4924d08ad)

**Comment by branchedelac** [comment]
@banerjek Are you using the latest release of the migration tools, or working from he repository? I merged some changes to main which have not yet been released.

**Comment by branchedelac** [comment]
The time stamps are indeed surprising. Hard to believe it would take 30 minutes to fetch acqMethods.

I had a quick look at what happens (silently) between logging Mapped Legacy Fields and fetching acq data.

![image](https://github.com/FOLIO-FSE/folio_migration_tools/assets/44287646/d2fd4888-8c22-4654-8684-2fef6da79eac)

What the second row here does is fetch all organizations from the tenant. (I'm going to add a log message for that to demystify.) So your theory about the 80 000 orgs being what takes time seems reasonable.

That doesn't explain why it would get stuck later, though -- after getting the acqMethod ref data map it should move on to other ref data maps, like locations.

Compare with this successful run:
https://github.com/FOLIO-FSE/migration_example/blob/main/iterations/test_run/reports/log_orders_transform_composite_orders_multiple_pols.log

**Comment by branchedelac** [comment]
I added a log message "Fetching Organizations from FOLIO...." to demystify what is taking so much time.

@banerjek I'm curious, are most of these 80 000 organizations actually associated with orders, or only a smaller subset? 

In case of the later, I wonder if it might be preferable to not fetch all organizations during setup, but rather fetch (and cache) them only if we find them in a legacy record. That is what I did for [users and items in the feefines mapper](https://github.com/FOLIO-FSE/folio_migration_tools/blob/ef76b4bdbd3814adb755cfafef0e8ca87fc3af36/src/folio_migration_tools/mapping_file_transformation/manual_fee_fines_mapper.py#LL236C9-L236C28) @bltravis @banerjek

**Comment by branchedelac** [comment]
> In case of the later, I wonder if it might be preferable to not fetch all organizations during setup, but rather fetch (and cache) them only if we find them in a legacy record. That is what I did for [users and items in the feefines mapper](https://github.com/FOLIO-FSE/folio_migration_tools/blob/ef76b4bdbd3814adb755cfafef0e8ca87fc3af36/src/folio_migration_tools/mapping_file_transformation/manual_fee_fines_mapper.py#LL236C9-L236C28)

@bltravis @banerjek I implemented this in https://github.com/FOLIO-FSE/folio_migration_tools/issues/628

**Comment by branchedelac** [comment]
We could definitely also make the Organization transformer generate an ID map, to be used exactly like the instance map. That could be very useful for a library like with 80 000 vendors, but less so for a library that works with 10 vendors which they added manually. So it could be optional/a configuration.

**Comment by branchedelac** [comment]
@banerjek can this be closed?
