### ISSUE TITLE
Object build routine require Instance, Holdings, Item prefix

### ISSUE THREAD

**Issue by banerjek** [FOLIO-FSE/folio_migration_tools#648]
Even for record types not being processed. 

Prefix should default to empty string rather than cause error if not present as it is not required by FOLIO and not desired by clients who use former IDs to populate HRIDs

**Comment by bltravis** [comment]
@banerjek Can you share the error output you're seeing? I'm trying to track down where it's checking for the presence of a prefix value, but I'm not seeing it.

**Comment by banerjek** [comment]
![MicrosoftTeams-image (2)](https://github.com/FOLIO-FSE/folio_migration_tools/assets/89302/030d1232-01af-4381-8d3a-d5a00f7a2d30)
