### ISSUE TITLE
Authority JSON spec refactored in version 27 of `mod-inventory-storage` 

### ISSUE THREAD

**Issue by ClintonWB-EBSCO** [FOLIO-FSE/folio_migration_tools#693]
The spec `"/ramls/authorities/authority.json"` has been refactored out of `mod-inventory-storage` in [this recent commit](https://github.com/folio-org/mod-inventory-storage/commit/9bcdb682ec0b13541d7a91340d13b76018169398#diff-51920e95310ebfbc1ae31709f3b95f89afffbf4f1a6e38e8b2b406e2fb6197ea) in version 27 of `mod-inventory-storage`, as part of the plan documented [on the wiki](https://wiki.folio.org/pages/viewpage.action?pageId=118270744).

[We are consuming this file in `rules_mapper_authorities.py`](https://github.com/FOLIO-FSE/folio_migration_tools/blob/4cc0b738c50d8bcdae114a9bfc2812f41f3b6176/src/folio_migration_tools/marc_rules_transformation/rules_mapper_authorities.py#L225)

They claim this was refactored into `mod-authority-manager`, currently known as `mod-entities-links`, but I was unable to find an analogous file there yet, with the authority spec defined/validated in Java.

We need to do something about this - for now, maybe loading an older version while we wait for things to change over?

**Comment by bltravis** [comment]
@ClintonWB-EBSCO Looking into this now. This is probably going to become a larger issue for us moving forward, as FOLIO's modules migrate to SpringWay from RMB/Vert.x.
