### ISSUE TITLE
Handle Address FOLIO Authorities Refactor rename `mod-entities-links` => `mod-authorities-manager`

### ISSUE THREAD

**Issue by ClintonWB-EBSCO** [FOLIO-FSE/folio_migration_tools#695]
In the fix for #694 for #693 , we reference `mod-entities-links`. It is planned to be renamed to `mod-authorities-manager` at some point; this issue is to record that, for when we get 404s on `mod-entities-links`, to speed recovery.

https://github.com/FOLIO-FSE/folio_migration_tools/blob/16ac579f14b232798a046870befde3f04a3c6f02/src/folio_migration_tools/marc_rules_transformation/rules_mapper_authorities.py#L231

**Comment by bltravis** [comment]
Closed by #694
