### ISSUE TITLE
MARC Bib transformer creates invalid preceding-succeeding-title records

### ISSUE THREAD

**Issue by btravisebsco** [FOLIO-FSE/folio_migration_tools#764]
If you transform a MARC bib with 780/785 preceding/succeeding title fields that do not have the subfields indicated by the mapping rules, the migration tools will happily create a preceding-succeeding-title record object that will post to FOLIO, but it will lack fields that FOLIO subsequently (and undocumented) expects it to have, specifically `title`.  The migration tools should discard preceding-succeeding-title objects that do not have a `title`. FOLIO's MARC-Bib mapper appears to handle it this way. Thoughts, @banerjek?

**Comment by banerjek** [comment]
Agreed they should be chucked if title isn't present -- the entire point of these fields is to provide another title access point.
