### ISSUE TITLE
Make sure that holdings callNumbers are correctly formatted for III non-boundwiths when there are boundwiths in the file

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/folio_migration_tools#98]
Currently, if some items are boundwiths, some non-boundwith holdings have their call numbers enclosed in brackets:

`{"id": "95024af1-d480-517d-85b8-9aeaa9ef26f7", "metadata": {"createdDate": "2021-12-17T16:29:36.475", "createdByUserId": "dce766bf-0fa4-4fa5-80d7-7759f5eaeb1f", "updatedDate": "2021-12-17T16:29:36.475", "updatedByUserId": "dce766bf-0fa4-4fa5-80d7-7759f5eaeb1f"}, "formerIds": ["i10000082"], "instanceId": "c10164b1-bd9e-5bf6-a84e-a290be463d82", "permanentLocationId": "6af5255d-b7f4-4f8f-81c8-080086ae1c6d", "callNumber": "['HB884.5 .P67 1984']", "holdingsTypeId": "4effa3a8-c991-4882-b1ee-2ea7c7487820"}`

This is not desirable, and needs to be fixed either in the script that parses III boudnwiths or the one that creates holdings.

Here is the record after it's been run through the parse-boubndwiths-service task, ie as it looks when main_items:
`['b1120008x']	i10000082		['HB884.5 .P67 1984']	0	clapp	-	-	10	12-19-2000 15:16	35002000000070											['HB884.5 .P67 1984']	False`

Here's the raw record from the library: 
`b1120008x			HB884.5 .P67 1984	0	clapp	-	-	10	12-19-2000 15:16	i10000082	35002000000070											HB884.5 .P67 1984	False`

**Comment by fontanka16** [comment]
I believe I have fixed this in the service task @branchedelac. It would be great if you could verify on your end.

**Comment by fontanka16** [comment]
Please reopen if not. I cannot see traces of this anymore. But my data might be different.

**Comment by branchedelac** [comment]
Here is the record after it's been run through the parse-boubndwiths-script, ie as it looks when main_items:
`['b1120008x']	i10000082		['HB884.5 .P67 1984']	0	clapp	-	-	10	12-19-2000 15:16	35002000000070											['HB884.5 .P67 1984']	False`

Here's the raw record from the library: 
`b1120008x			HB884.5 .P67 1984	0	clapp	-	-	10	12-19-2000 15:16	i10000082	35002000000070											HB884.5 .P67 1984	False`

I will test and verify!

**Comment by branchedelac** [comment]
I now get this result (same record as above):

`{"id": "95024af1-d480-517d-85b8-9aeaa9ef26f7", "metadata": {"createdDate": "2022-04-28T17:05:42.052", "createdByUserId": "dce766bf-0fa4-4fa5-80d7-7759f5eaeb1f", "updatedDate": "2022-04-28T17:05:42.052", "updatedByUserId": "dce766bf-0fa4-4fa5-80d7-7759f5eaeb1f"}, "formerIds": ["i10000082"], "instanceId": "c10164b1-bd9e-5bf6-a84e-a290be463d82", "permanentLocationId": "6af5255d-b7f4-4f8f-81c8-080086ae1c6d", "callNumber": "'HB884.5 .P67 1984'", "holdingsTypeId": "03c9c400-b9e3-4a07-ac0e-05ab470233ed", "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264"}`

The brackets are gone, but the quotes are still there.

**Comment by branchedelac** [comment]
> Please reopen if not. I cannot see traces of this anymore. But my data might be different.

What does your data look like?

**Comment by branchedelac** [comment]
Similar to the instance ID, the call number for the "normal case" is in folio_rec["callNumber"][0].

**Comment by branchedelac** [comment]
Hopefully resolved -- for the example data above, yes -- by https://github.com/FOLIO-FSE/service_tools/pull/16.

**Comment by fontanka16** [comment]
@branchedelac was it solved previously or did you do anything? Could you add a comment on the reason for why you reopened and closed it?

**Comment by branchedelac** [comment]
See this comment and below: https://github.com/FOLIO-FSE/folio_migration_tools/issues/98#issuecomment-1113161827

I tried to explain in the comments how it wasn’t working, using the same example as originally. Could you help me understand what more information is needed?

The linked pull request which should show what I did to fix it.
